# Generated by Django 4.2.2 on 2023-06-17 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='addres',
            new_name='address',
        ),
    ]
